package com.dscoding.takenoteapp.utils

object Constants {
    const val NOTE_ID_ARG = "noteId"
    const val NOTE_COLOR_ARG = "noteColor"
    const val DATABASE_NAME = "note_db"
    const val DATASTORE_NAME = "settings_ds"
    const val NAVIGATION_ANIMATION_DURATION = 250
    const val NAVIGATION_SLIDE_HORIZONTAL_ANIMATION_TARGET_OFFSET = 1600
    const val FIREBASE_ANALYTICS_EVENT_ADD_NOTE = "ADD_NOTE"
    const val FIREBASE_ANALYTICS_EVENT_ADD_NOTE_COLOR = "ADD_NOTE_COLOR_PARAM"
    const val FIREBASE_ANALYTICS_EVENT_EDIT_NOTE = "EDIT_NOTE"
    const val FIREBASE_ANALYTICS_EVENT_DELETE_NOTE = "DELETE_NOTE"
    const val FIREBASE_ANALYTICS_EVENT_RATE_APP = "RATE_APP"
    const val FIREBASE_ANALYTICS_EVENT_SWAP_THEME = "SWAP_THEME"
    const val FIREBASE_ANALYTICS_EVENT_SWAP_THEME_PARAM = "SWAP_THEME_PARAM"
}