package com.dscoding.takenoteapp.utils

object TestTags {
    // Notes Screen
    const val ORDER_SECTION = "ORDER_SECTION"
    const val ORDER_TITLE_RADIO_BUTTON = "ORDER_TITLE_RADIO_BUTTON"
    const val ORDER_ASCENDING_RADIO_BUTTON = "ORDER_ASCENDING_RADIO_BUTTON"

    // Add Edit Note Screen
    const val TITLE_TEXT_FIELD = "TITLE_TEXT_FIELD"
    const val CONTENT_TEXT_FIELD = "CONTENT_TEXT_FIELD"

    // Settings Screen
    const val THEME_YELLOW_RADIO_BUTTON = "THEME_YELLOW_RADIO_BUTTON"
    const val SHOW_GREETING_SWITCH = "SHOW_GREETING_SWITCH"
    const val SHOW_GREETING_SWITCH_VALUE = "SHOW_GREETING_SWITCH_VALUE"
    const val TWENTY_FOUR_HOUR_SWITCH = "TWENTY_FOUR_HOUR_SWITCH"
    const val TWENTY_FOUR_HOUR_SWITCH_VALUE = "TWENTY_FOUR_HOUR_SWITCH_VALUE"
}